// Selectors for Header

export default class BlogPage_selectors {

    readButtonForFirstArticle = "#blog-search-result--item-0 > div.rating-button > a"
    readButtonForSecondArticle = "#blog-search-result--item-1 > div.rating-button > a"
    readButtonForThirdArticle = "#blog-search-result--item-2 > div.rating-button > a"
    landscapeDesignSection = ".tablet-large-view > li:nth-child(5) > map > area:nth-child(1)"
    firstItemSearchResult = "#blog-search-result--item-0 > .title > a" 
    secondItemSearchResult = "#blog-search-result--item-1 > .title > a"
    thirdItemSearchResult = "#blog-search-result--item-2 > .title > a"
    articleNumberFirstPath = "#blog-search-result--item-"
    articleNumberSecondPath = " > .title > a"
    articleNumberButtonFirstPath = "#blog-search-result--item-"
    articleNumberButtonSecondPath = " div.rating-button > a"
    searchInputFieldOneArticle = "#search"
    searchIconOneArticle = ".submit-btn > .icon"
    crossSearchIconOneArticle = ".close"
    socialIconFirstItemOneArticle = ".socials.top > a:nth-child(1)"
    socialIconSecondItemOneArticle = ".socials.top > a:nth-child(2)"
    socialIconOneArticle = ".socials.top"
    socialItemOneArticle = ".social-item"
    ratingOneArticle = ".blog-article-rating"
    switcherCommentsOneArticle = "#switcher_comments"
    numberCommentsOneArticle = ".comments-number"
    commentsAvatarOneArticle = ".comment-image > img"
    commentsInputFieldOneArticle = ".comment > .form-group > textarea"
    commentsSubmitButtonOneArticle = ".comment-btn"
    blogPopularBlockOneArticle = ".forum-block"
    rubricsBlockOneArticle = ".rubrics"
    interestingBlockOneArticle = ".sidebar > .green-textarea"
    flowerDayBlockOneArticle = ".col-sidebar > div > div.flower-day.flower-day--sidebar > div"
    advertisingLinkOneArticle = ".banners > .button"
    advertisementBanner = ".banners-wrap"
    advertisementImage = ".bg-img"
    headImageOneArticle = ".article-image > img"
    titleOneArticle = ".blog-article-title"
    findYourFlowerLinkOneArticle = ".flower-day--inner > .link-icon"
    interestingTopicInputFieldOneArticle = ".sidebar > .green-textarea > .form-block > #interesting_topic > .form-group > textarea"
    interestingTopicSubmitButtonOneArticle = ".sidebar > .green-textarea > .form-block > #interesting_topic > .form-group > .submit-btn"
   
} 